name: CI with Cache Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: prime-cache-f1617ba
      id: cache-step
      uses: actions/cache@v4
      with:
        path: node_modules
        key: cache-f1617ba
    
    - name: Echo cache result
      run: |
        echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
    
    - name: Install dependencies
      if: steps.cache-step.outputs.cache-hit != 'true'
      run: npm install
    
    - name: Test
      run: npm test || echo "No tests"


